version: "3.8"
services:
  server:
    image: legiahoangthien/webtravel-backend:latest
    restart: always
    env_file:
      - /backend/.env
    ports:
      - "4000:4000"
  client:
    image: legiahoangthien/webtravel-frontend:latest
    restart: always  # Chế độ khởi động lại container tự động nếu có lỗi
    env_file:
      - /frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - server
