version: "3.8"
services:
  server:
    image: legiahoangthien/nestjs-backend:latest
    restart: always
    env_file:
      - /backend/.env
    ports:
      - "5000:5000"

  client:
    image: legiahoangthien/react-frontend:latest
    restart: always  # Chế độ khởi động lại container tự động nếu có lỗi
    env_file:
      - /frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - server
